image: docker

services:
  - docker:stable-dind

stages:
  - build
  - test

before_script:
  - docker version
  - apk add --no-cache docker-compose
  - docker-compose version

build:
  stage: build
  script:
    - echo "Building ..."

test:
  stage: test
  script:
    - echo "Testing ..."
