image: docker

services:
  - docker:stable-dind

stages:
  - build
  - test

before_script:
  - docker version
  - apk add --no-cache docker-compose
  - docker-compose version

build:
  stage: build
  script:
    - echo "Building ..."
    - docker login -u gitlab-ci-token -p $REGISTRY_TOKEN $REGISTRY
    - docker-compose build
    - docker-compose push

test:
  stage: test
  script:
    - echo "Testing ..."
