import React, {Component} from 'react';
import MenuBar from "../../../components/MenuBar";
import Avatar from "../segments/Avatar";
import {withCookies} from "react-cookie";
import Footer from "../../../components/Footer";
import ContentView from "./components/ContentView";
import { AuthenticationContext } from "../../../AuthenticationContext";

class PrivateAccountPage extends Component {
    static contextType = AuthenticationContext;

    /**
     * This component will provide an account as well an loading screen.
     * It will also need to have cookies to work with the user token.
     * @param props
     */
    constructor(props) {
        super(props);
        this.state = {
            account: {},
            loading: true,
            menuHeight: 65 // the magic number given by size='large' in MenuBar (generated by semantic ui)
        }
    }

    /**
     * This method pulls the data of the calling user after the component did mount.
     * The calling account is identified by the user-token.
     */
    componentDidMount() {
        this.context.get(process.env.REACT_APP_API_URL.concat("/accounts/show/own/")).then(result => {
            if (result.status === 200) {
                this.setState({
                    account: result.data[0],
                    loading: false
                })
            }
        }).catch(error => {
            this.setState({
                loading: true
            })
        })
    }

    /**
     * While the data is loaded a loading screen will be shown.
     * After loading the account will be displayed.
     * @returns {JSX.Element}
     */
    render() {
        if (this.state.loading)
            return <div>
                Fetching ...
            </div>
        return (
            <div>
                <MenuBar/>
                <Avatar
                    forPublicUse={false}
                    image={process.env.REACT_APP_API_URL.concat(this.state.account.image)}
                    username={this.state.account.user.username}
                    biography={this.state.account.biography}
                />
                <ContentView
                    menuOffset={this.state.menuHeight}
                    account={this.state.account}/>
                <Footer/>
            </div>
        );
    }
}

export default withCookies(PrivateAccountPage);