import React, { Component, createRef } from 'react';
import Heading from "./segments/Heading";
import Footer from "../../components/Footer";
import MenuBar from "../../components/MenuBar";
import ContentView from "./segments/ContentView";
import { withCookies } from "react-cookie";
import { AuthenticationContext } from "../../AuthenticationContext";

/**
 * Constant size of loading statements
 */
const pageSize = 10;

class MainPage extends Component {
    static contextType = AuthenticationContext;

    /**
     * This component represents the main page of solar.
     * In this component the main communication takes part.
     */
    constructor(props) {
        super(props);
        this.state = {
            loading: true,
            observerMounted: false,
            results: { data: [] },
            prevPage: 0,
            menuHeight: 65 // the magic number given by size='large' in MenuBar (generated by semantic ui)
        };

        this.updateReactions = this.updateReactions.bind(this);

        this.loadingRef = createRef();
    }

    /**
     * Gets called before mounting the component.
     */
    componentDidMount() {
        this.loadNextStatements();

        var options = {
            root: null,
            rootMargin: "0px",
            threshold: 1.0
        };

        this.observer = new IntersectionObserver(
            this.handleObserver.bind(this),
            options
        );

        if (this.loadingRef.current) {
            this.observer.observe(this.loadingRef.current);
            this.setState({ observerMounted: true });
        }
    }

    componentDidUpdate() {
        if (!this.state.observerMounted && this.loadingRef.current) {
            this.observer.observe(this.loadingRef.current);
            this.setState({ observerMounted: true });
        }
    }

    /**
     * This method loads the feed from the backend.
     */
    loadNextStatements() {
        const { prevPage } = this.state;
        let page = prevPage + 1;

        this.context.get(process.env.REACT_APP_API_URL.concat("/contents/statements/feed/pagination"), { page: page, size: pageSize }).then(result => {

            if (result.status === 200) {
                const { results } = this.state;
                if (result.data.data.length)
                    results.data = results.data.concat(result.data.data);
                else
                    page = page - 1;

                this.setState({
                    results,
                    loading: false,
                    prevPage: page
                });
            }
        }).catch(error => {
            this.setState({ loading: true });
        });
    }

    handleObserver = (entities) => {
        const target = entities[0];
        if (target.isIntersecting)
            this.loadNextStatements();
    };

    /**
     * This method updates the reactions on the main page.
     * In this context an reaction is made by those the calling account follows.
     * @param reaction to be added (simple statement).
     */
    updateReactions = (reaction) => {
        let results = { ...this.state.results };
        results["data"] = [reaction].concat(results["data"]);
        this.setState({ results });
    }

    /**
     * This component represents the main page of SolAr.
     * @returns {JSX.Element}
     */
    render() {
        if (this.state.loading) {
            return <div>
                Fetching ...
            </div>
        }
        return (
            <div>
                <MenuBar />
                <Heading />
                <ContentView
                    updateReactions={this.updateReactions}
                    menuOffset={this.state.menuHeight}
                    results={this.state.results}
                    loadMore={this.loadNextStatements}
                >
                    <div ref={this.loadingRef} style={{ height: 20 }}></div>
                </ContentView>
                <Footer />
            </div>
        );
    }
}

export default withCookies(MainPage);