import React, {Component} from 'react';
import Heading from "./segments/Heading";
import SocialExplorer from "./segments/SocialExplorer";
import Footer from "../../components/Footer";
import MenuBar from "../../components/MenuBar";
import AccountExplorer from "./segments/AccountExplorer";
import ContentView from "./segments/ContentView";
import {withCookies} from "react-cookie";
import axios from "axios";


class MainPage extends Component {


    /**
     * This component represents the main page of solar.
     * In this component the main communication takes part.
     */
    constructor(props) {
        super(props);
        this.state = {
            loading: true,
            results: {},
            menuHeight: 65 // the magic number given by size='large' in MenuBar (generated by semantic ui)
        }
        this.updateReactions = this.updateReactions.bind(this);
    }

    /**
     * This method loads the feed from the backend.
     * Todo: Replace this with an SSE stream.
     */
    componentDidMount() {
        const {cookies} = this.props
        const utkn = cookies.get("utkn")
        axios.get(process.env.REACT_APP_API_URL.concat("/contents/statements/feed/"),
            {
                headers: {
                    'Authorization': 'Token '.concat(utkn)
                }
            }).then(result => {
            if (result.status === 200) {
                this.setState({
                    results: result,
                    loading: false
                })
            }
        }).catch(error => {
            this.setState({
                loading: true
            })
        })
    }

    /**
     * This method updates the reactions on the main page.
     * In this context an reaction is made by those the calling account follows.
     * @param reaction to be added (simple statement).
     */
    updateReactions = (reaction) => {
        let results = {...this.state.results}
        results["data"] = [reaction].concat(results["data"])
        this.setState({results})
    }

    /**
     * This component represents the main page of SolAr.
     * @returns {JSX.Element}
     */
    render() {
        if (this.state.loading) {
            return <div>
                Fetching ...
            </div>
        }
        return (
            <div>
                <MenuBar/>
                <Heading/>
                <SocialExplorer/>
                <AccountExplorer/>
                <ContentView
                    updateReactions={this.updateReactions}
                    menuOffset={this.state.menuHeight}
                    results={this.state.results}
                />
                <Footer/>
            </div>
        );
    }
}

export default withCookies(MainPage);