import React, {Component} from 'react';
import Heading from "./segments/Heading";
import SocialExplorer from "./segments/SocialExplorer";
import Footer from "../../components/Footer";
import MenuBar from "../../components/MenuBar";
import AccountExplorer from "./segments/AccountExplorer";
import ContentView from "./segments/ContentView";


class MainPage extends Component {


    /**
     * This component represents the main page of solar.
     * In this component the main communication takes part.
     */
    constructor(props) {
        super(props);
        this.state = {
            menuHeight: 65 // the magic number given by size='large' in MenuBar (generated by semantic ui)
        }
    }

    /**
     * This component represents the main page of SolAr.
     * @returns {JSX.Element}
     */
    render() {
        return (
            <div>
                <MenuBar/>
                <Heading/>
                <SocialExplorer/>
                <AccountExplorer/>
                <ContentView menuOffset={this.state.menuHeight}/>
                <Footer/>
            </div>
        );
    }
}

export default MainPage;