import React, {Component} from 'react';
import MenuBar from "../../components/MenuBar";
import Heading from "./segments/Heading";
import {PropTypes} from "prop-types";
import ContentView from "./segments/ContentView";
import axios from "axios";
import {withCookies} from "react-cookie";

class TopicPage extends Component {

    /**
     * This component is for the conversation around specific topics.
     * Therefore the url must provide the tag
     * @type {{match: *}}
     */
    static propTypes = {
        match: PropTypes.shape({
            params: PropTypes.shape({
                tag: PropTypes.string.isRequired
            })
        }),
    };

    /**
     * This component is for the conversation around specific topics.
     * It should be possible to directly add statement or to react to certain positions or reactions.
     * @param props
     */
    constructor(props) {
        super(props);
        this.state = {
            tag: this.props.match.params.tag,
            results: {},
            loading: true,
            menuHeight: 65 // the magic number given by size='large' in MenuBar (generated by semantic ui)
        }
    }

    componentDidMount() {
        const {cookies} = this.props
        const utkn = cookies.get("utkn")
        axios.get(process.env.REACT_APP_API_URL.concat("/contents/statements/with/hashtag/"),
            {
                headers: {
                    'Authorization': 'Token '.concat(utkn)
                },
                params: {
                    q: this.state.tag
                }
            }).then(result => {
            if (result.status === 200) {
                this.setState({
                    results: result,
                    loading: false
                })
                console.log(this.state.results)
            }
        }).catch(error => {
            this.setState({
                loading: false
            })
            console.error(error)
        })
    }

    /**
     * This component shows everything about an topic
     * @returns {JSX.Element}
     */
    render() {
        if (this.state.loading)
            return <div>
                Fetching ...
            </div>
        return (
            <div>
                <MenuBar/>
                <Heading tag={this.state.tag}/>
                <ContentView
                    menuOffset={this.state.menuHeight}
                    results={this.state.results}
                />
            </div>
        );
    }
}

export default withCookies(TopicPage);