# Generated by Django 3.1.2 on 2020-12-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='relationships',
        ),
        migrations.AddField(
            model_name='account',
            name='related_to',
            field=models.ManyToManyField(blank=True, default=None, related_name='related_by', through='accounts.Relationship', to='accounts.Account'),
        ),
    ]
