# Generated by Django 3.1.2 on 2020-12-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201208_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='account/default/Argunaut.png', upload_to='account/images'),
        ),
    ]
