# Generated by Django 3.1.2 on 2020-12-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='biography',
            field=models.CharField(default='Hey there my name is <django.db.models.query_utils.DeferredAttribute object at 0x104388940> and this is my profile!', max_length=1000),
        ),
    ]
