# Generated by Django 3.1.2 on 2020-12-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='biography',
            field=models.CharField(default='Hey there, nice to meet you!', max_length=1000),
        ),
    ]
