# Generated by Django 3.1.2 on 2021-01-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20210104_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatementTagging',
            new_name='HashtagTagging',
        ),
    ]
