# Generated by Django 3.1.2 on 2021-01-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201228_2033'),
        ('contents', '0003_auto_20210105_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtagtagging',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.statement'),
        ),
        migrations.CreateModel(
            name='AccountTagging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='accounts.account')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.statement')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='statement',
            name='mentioned',
            field=models.ManyToManyField(blank=True, default=None, related_name='mentions', through='contents.AccountTagging', to='accounts.Account'),
        ),
    ]
