# Generated by Django 3.1.2 on 2021-02-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20210105_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vote', models.PositiveSmallIntegerField(choices=[(1, 'Like'), (2, 'Dislike')], default=1)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='contents.statement')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='contents.statement')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='statement',
            name='reactions',
            field=models.ManyToManyField(blank=True, default=None, related_name='reaction_of', through='contents.Reaction', to='contents.Statement'),
        ),
    ]
