# Generated by Django 3.1.2 on 2021-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20210213_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statement',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='reaction',
            name='vote',
            field=models.PositiveSmallIntegerField(choices=[(1, 'like'), (2, 'dislike')], default=1),
        ),
    ]
