import React, {Component} from 'react';
import {Form, Grid, Image, Message, Segment} from "semantic-ui-react";
import logo from '../../resources/logo.jpg'
import {NavLink, Redirect} from "react-router-dom";
import {Cookies, withCookies} from "react-cookie";
import axios from "axios";
import {instanceOf} from "prop-types";

class LoginForm extends Component {
    /**
     * This component is the login form to authenticate an user.
     * Furthermore this component will set the user token, generated by the backend, in the cookies.
     * @type {{cookies: Validator<NonNullable<Cookies>>}}
     */
    static propTypes = {
        cookies: instanceOf(Cookies).isRequired
    };

    /**
     * The login form will need the username as well as the password for authentication.
     * @param props is used for the cookies.
     */
    constructor(props) {
        super(props);
        this.state = {
            success: false,
            errorUserField: false,
            errorPasswordField: false,
            username: "",
            password: ""
        }
        this.handleChange = this.handleChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
    }

    /**
     * This method will handle the changes in the password and username field.
     * It will update the state.
     * @param event of typing in the username or password.
     */
    handleChange = (event) => {
        event.preventDefault();
        if (event.target.name === "usernameInput")
            this.setState({username: event.target.value})
        else if (event.target.name === "passwordInput")
            this.setState({password: event.target.value})
    }

    /**
     * This method is for the validation of the provided user data.
     * It will send a request with the provided data to the backend.
     * The backend will then validate the data.
     * If the data is valid the user-token will we stored in the cookies.
     * Otherwise the errors will be shown to the user.
     * @param event of typing in the data.
     */
    handleSubmit = (event) => {
        event.preventDefault();
        const {cookies} = this.props
        axios.post(process.env.REACT_APP_API_URL.concat("/authentication/login/"), {
            "username": this.state.username,
            "password": this.state.password
        }).then(result => {
            if (result.status === 200 && result.data.token) {
                cookies.remove("utkn")
                cookies.set("utkn", result.data.token, {sameSite: 'Lax'})
                this.setState({
                    success: true
                })
            }
        }).catch(error => {
            const response = error.response.data;
            const keys = Object.keys(response)
            this.setState({
                errorUserField: keys.includes("user") || keys.includes("username"),
                errorPasswordField: keys.includes("password")
            })
        })

    }

    /**
     * If the login succeeded the user will be redirected to the main page.
     * Otherwise the errors will be presentend.
     * @returns {JSX.Element}
     */
    render() {
        if (this.state.success)
            return <Redirect to={{pathname: '/'}}/>
        return (
            <div>
                <Grid textAlign='center' style={{height: '100vh'}} verticalAlign='middle'>
                    <Grid.Column style={{maxWidth: "70%"}}>
                        <Image style={{maxWidth: "70%", marginBottom: "3em"}}
                               src={logo}
                               circular
                               size="small"
                               centered/>
                        <Form size='large'
                              error={this.state.errorUserField || this.state.errorPasswordField}
                              onSubmit={this.handleSubmit}>
                            <Segment raised>
                                <Form.Input
                                    name="usernameInput"
                                    fluid
                                    error={this.state.errorUserField}
                                    icon='user'
                                    iconPosition='left'
                                    placeholder='Username'
                                    type='text'
                                    value={this.state.username}
                                    onChange={this.handleChange}
                                />
                                <Form.Input
                                    name="passwordInput"
                                    fluid
                                    error={this.state.errorPasswordField}
                                    icon='lock'
                                    iconPosition='left'
                                    placeholder='Password'
                                    type='password'
                                    value={this.state.password}
                                    onChange={this.handleChange}
                                />
                                <Form.Button
                                    type='submit'
                                    secondary
                                    fluid
                                    size='large'
                                >
                                    Login
                                </Form.Button>

                                <Message error>
                                    <Message.Header>
                                        Oh no! Please check your data.
                                    </Message.Header>
                                </Message>
                            </Segment>
                        </Form>
                        <Message>
                            New to us? <NavLink to="/signup">Sign Up!</NavLink>
                        </Message>
                    </Grid.Column>
                </Grid>
            </div>
        );
    }

}

export default withCookies(LoginForm);