upstream solar {
    server  solar:9000;
}

server {
    listen 80;
    server_name solar.marc-feger.de;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name solar.marc-feger.de;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/solar.marc-feger.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/solar.marc-feger.de/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location ~ ^/(admin|search|accounts|authentication|contents)/?(.*)$ {
        try_files $uri @proxy_solar;
    }

     location @proxy_solar {
        include /etc/nginx/uwsgi_params;
        uwsgi_pass solar;

        uwsgi_param Host $host;
        uwsgi_param X-Real-IP $remote_addr;
        uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
        uwsgi_param X-Forwarded-Proto $http_x_forwarded_proto;
    }

    location / {
        root /var/www/fairing;
        try_files $uri $uri/ /index.html;
    }

    # no cache for nginx
    location ~* (service-worker\.js)$ {
        add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        expires off;
        proxy_no_cache 1;
    }

    location /django_static {
        autoindex on;
        alias /code/django_static;
    }
     location /media {
        autoindex on;
        alias /code/media;
    }
}
